version: '2'
  collapsible-optimism:
    image: builder555/collapsible-optimism:latest
    privileged: true
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.sysfs: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.procfs: 1
